# Config
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elev
  unit_system: metric
  time_zone: Europe/Stockholm
  external_url: !secret external_url
  internal_url: !secret internal_url
  

# Text to speech
tts:
  - platform: google_translate

# Enable mobile app integration
mobile_app:

# Enable frontend (include for themes)
frontend: #!include frontend.yaml

# Enable frontend configiration
config:

# Enable history
history:

# Enable logbook
logbook:

# Enable map
map:

# Enable sun status
sun:

# Enable system health integration
system_health:

# HA update notifier
updater:

# Lifx lightbulbs
lifx:

# LG TV
webostv:
  host: !secret ip_lgtv
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_lgtv
  customize:
    sources:
      - youtube
      - netflix

media_player:

notify:

# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Wake on lan
wake_on_lan:

# PC switch
switch:
  - platform: wake_on_lan
    name: Desktop
    host: !secret ip_pqdesktop
    mac: !secret mac_pqdesktop

# Map zones
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
person: !include persons.yaml
device_tracker: !include device_trackers.yaml



# ----- Components -----
#mqtt:
#wake_on_lan:

#light:
#  - platform: lifx
  
#media_player:
#  - platform: webostv
#    host: !secret ip_lgtv
#    name: TV
#    customize:
#      sources:
#        - hdmi1
#    turn_on_action:
#      service: wake_on_lan.send_magic_packet
#      data:
#        mac: !secret mac_lgtv
#  - platform: mpchc
#    host: !secret ip_pqdesktop
#    
#device_tracker:
#  - platform: luci
#    host: !secret ip_router
#    username: root
#    password: !secret router_pw
#    interval_seconds: 3
#    consider_home: 10
#    track_new_devices: no
#
#switch:
#  - platform: wake_on_lan
#    name: "Computer"
#    mac_address: !secret mac_pqdesktop
#    host: !secret ip_pqdesktop
#    turn_off:
#      service: shell_command.computer_sleep