# ----- Views -----

#default_view:
#    view: yes
#    entities:
#      - media_player.tv
      
automation:
  view: yes
  entities:
    - group.all_automations
    
users:
  entities:
    - device_tracker.pqphone
    - device_tracker.eqphone